framework:
    messenger:
        failure_transport: failed
        reset_on_message: true
        transports:
            failed: 'doctrine://default?queue_name=failed'
            async:
                dsn: 'doctrine://default?auto_setup=0&queue_name=async'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 1
                    delay: 1000
                    multiplier: 2
                    max_delay: 3000
            priority:
                dsn: 'doctrine://default?auto_setup=0&queue_name=priority'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 1
                    delay: 1000
                    multiplier: 2
                    max_delay: 3000

        routing:
           App\Message\SentLetter: async
           App\Message\SentPackage: priority

        buses:
            messenger.bus.default:
                middleware:
                    - App\Middleware\MessagesLogger
